### ISSUE TITLE
Issue with new version of GUROBI

### ISSUE THREAD

**Issue by atshehu1776** [mit-acl/mader#14]
Hi,
Thank you for this fantastic package.
I had the following error while running the package with ROS Noetic on Ubuntu 20.04.

![Screenshot from 2022-12-07 18-28-56](https://user-images.githubusercontent.com/33266976/206257075-f02cfe3c-d0b3-4ae8-9d12-98e4407f4712.png)

**Comment by jtorde** [comment]
Hi! What Gurobi version are you using?

Also, are you using the last commit of this repo? (5e9fdf1583ce4e9fcd9b138cf50fa9c059249c97)

**Comment by jtorde** [comment]
I am closing this for now, feel free to reopen if you are still finding this issue
