### ISSUE TITLE
the input and output of mader

### ISSUE THREAD

**Issue by 001zwzwzw** [mit-acl/mader#16]
hello I have great interest in mader
so i want to know the input and output of mader in real world,such as depth image or lidar point cloud?

**Comment by jtorde** [comment]
Hi @001zwzwzw,

The input of MADER can be either a depth image or a point cloud. However, MADER requires that you run a clustering algorithm (or something similar), that obtains a polyhedral approximation of the obstacles. This is already implemented in the file [tracker_predictor.cpp](https://github.com/mit-acl/panther/blob/master/panther/src/tracker_predictor.cpp) of the [PANTHER](https://github.com/mit-acl/panther) repo

I'm closing this for now, but feel free to reopen it if needed
