### ISSUE TITLE
Trajectory Generation done in Octopus Search

### ISSUE THREAD

**Issue by minghancmh** [mit-acl/mader#17]
Hi,

Just wondering why the trajectories generated in octopus search does not actually reach the final end point? 

Thanks!

**Comment by minghancmh** [comment]
Found out that modifying params.Ra yielded a trajectory that reaches the endpoint. Just curious as to what this Ra is ?

**Comment by jtorde** [comment]
Hi @minghancmh,

Ra is the radius of a sphere in which the algorithm will try to find a trajectory. Octopus Search will not create any control points that lie outside that sphere (see [this line](https://github.com/mit-acl/mader/blob/master/mader/src/octopus_search.cpp#L974)). 

Octopus Search will try to find a trajectory that finishes close to the goal (but it does not have to be exactly the goal). The trajectory obtained by Octopus Search will be used as initial guess in the optimization. In this optimization, the distance between the endpoint of the trajectory and the goal is minimized (see Section V-D of the [paper](https://arxiv.org/pdf/2010.11061.pdf))

**Comment by jtorde** [comment]
I'm closing this for now, but feel free to reopen it if needed
