### ISSUE TITLE
[Question]  Are there any references to the basis transformations are calculated?

### ISSUE THREAD

**Issue by GPrathap** [mit-acl/mader#18]
Hi there, 

I checked https://github.com/mit-acl/minvo but could not find how these basis transformations were obtained 

BSPLINE to MINVO POSITION https://github.com/mit-acl/mader/blob/5e9fdf1583ce4e9fcd9b138cf50fa9c059249c97/mader/include/mader_types.hpp#L192

BSPLINE to BEZIER POSITION https://github.com/mit-acl/mader/blob/5e9fdf1583ce4e9fcd9b138cf50fa9c059249c97/mader/include/mader_types.hpp#L192

if you can provide any hint, it would be great.

Thanks,

**Comment by jtorde** [comment]
Hi @GPrathap,

Those transformations were obtained using Eq. 5 of the MINVO paper: https://arxiv.org/pdf/2010.10726.pdf

To derive them, you can use the functions  [getA_MV.m](https://github.com/mit-acl/minvo/blob/master/src/solutions/getA_MV.m), [getA_Be.m](https://github.com/mit-acl/minvo/blob/master/src/utils/bezier_bspline/getA_Be.m), [getA_BS.m](https://github.com/mit-acl/minvo/blob/master/src/utils/bezier_bspline/getA_BS.m), and [computeMatrixForClampedUniformBSpline.m](https://github.com/mit-acl/minvo/blob/master/src/utils/bezier_bspline/computeMatrixForClampedUniformBSpline.m) of the MINVO repository

For example, to obtain [this](https://github.com/mit-acl/mader/blob/5e9fdf1583ce4e9fcd9b138cf50fa9c059249c97/mader/include/mader_types.hpp#L194) transformation, you can use this matlab code: 

```
computeMatrixForClampedUniformBSpline(3,0,[0,1])*inv(getA_MV(3,[0,1]))
```

I hope this helps!

**Comment by GPrathap** [comment]
Hi @jtorde , 

Yep, thank you for your prompt response! I will look into it

**Comment by jtorde** [comment]
Perfect! I'm gonna close this for now, but feel free to reopen it if you are having any issues
