### ISSUE TITLE
Using NLOPT optimizer

### ISSUE THREAD

**Issue by hs1110** [mit-acl/mader#19]
Hi,
I'm interested in running Mader with the NLOPT optimizer. Could you advise me on the most suitable commit version to use for this purpose? Your assistance would be greatly appreciated.
Best, Hadar.

**Comment by jtorde** [comment]
Hi, 

MADER's performance using NLOPT is much worse than with Gurobi. However, if you want to use NLOPT you can do so by following the instructions specified in the "Note" at the end of the readme.

**Comment by hs1110** [comment]
OK, I'll give it a try.
Could you please specify the recommended versions of Ubuntu and ROS that I should use?
Thanks!
