### ISSUE TITLE
single_agent_simulation 

### ISSUE THREAD

**Issue by duzhenpeng** [mit-acl/mader#21]
I can successfully make the package of mader， but when I run the follow cmd, I encountered a fetal problem.
roslaunch mader single_agent_simulation.launch

[SQ01s/mader-8] process has died [pid 30973, exit code -6, cmd /home/dzp/mader_ws/devel/lib/mader/mader_node ~state:=state ~who_plans:=who_plans ~term_goal:=term_goal ~traj:=traj ~goal:=goal ~setpoint:=setpoint __name:=mader __log:=/home/dzp/.ros/log/497f92e2-8a1f-11ee-bb0b-e89c257f2e5e/SQ01s-mader-8.log].
log file: /home/dzp/.ros/log/497f92e2-8a1f-11ee-bb0b-e89c257f2e5e/SQ01s-mader-8*.log

![Screenshot from 2023-11-23 16-44-38](https://github.com/mit-acl/mader/assets/69375714/0f9a0161-372e-4be5-8955-741659cea5b7)

**Comment by duzhenpeng** [comment]
![Uploading Screenshot from 2023-11-23 16-44-38.png…]()

**Comment by gooodlkk** [comment]
I also encountered the same problem. How did you solve it?

**Comment by XXLiu-HNU** [comment]
Same problem, have you solved it？

**Comment by jtorde** [comment]
Hi @XXLiu-HNU, 

Have you installed Gurobi correctly? Try to run `gurobi.sh` from the terminal to check it.
